### ISSUE TITLE
Improve the process for building under Windows using Visual C++

### ISSUE THREAD

**Issue by SeanFarrow** [awslabs/amazon-kinesis-video-streams-producer-c#109]
Hi,

As a new user of this library, I have tries to build this under Windows using visual C++ and am getting to the point where it looks for pkg-config.

I get an error that the pkg-config --version command isn't working. I suspect this is more of a Cmake issue, but wondered whether it would be worth improving the build in any case.

Several things strike me:
Firstly, should a package manager such as vcpkg be used, that way dependencies are built only once.
Secondly, it would be nice to be able to build this using dynamic linking. Whilst static linking is great most of the time, I have had cases where I would have needed to link the library dynamically.

Finally, The build assumes  Visual Studio 2017 is present, it would be nice if VSWhere was used to determine which version of visual studio was present onthe system and use the highest version available.

I'm happy to do the work, if there would be interest.

**Comment by MushMal** [comment]
@SeanFarrow thanks for the offer. We are certainly looking for ways to improve the repo, including the build.

What are your thoughts around the Windows? Currently, we try to minimize the platform specificity in the CMakeList.txt but in general, we are using a CMake based build. Are you suggesting to use a CMD and CMake combination to set the parameters such as the VS location? 

We can certainly iterate over your PR if you submit it.

**Comment by SeanFarrow** [comment]
@MushMal , essentially, yes.

I'm suggesting a CMD, power shell and then a C make build system that uses VCPKG to resolve all￼ dependencies to deal with the build on windows and then potentially using bash to do something very similar on other platforms.

I have a few days off next week, so I'll try and put a PR together then.￼

**Comment by MushMal** [comment]
Prior the new repository, the code was in a single repository and we had a pair of scripts - a bash script and a cmd to drive the dependency build/package manager/etc for given platforms. This had a whole set of their own issues, primarily around the build of the dependencies and pulling down some build tools. Since then, we attempted to move away from scripting in favor of CMake build only (with the exception of building GStreamer for CPP SDK for Windows TravisCI runs: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/.github/build_windows.bat)

I am wondering if folks could chime in on this. While CMake syntax is not for the faint hearted, it's possible to run these commands in CMake and not use shell scripts?

**Comment by SeanFarrow** [comment]
I don’t know Cmake that well, but am happy to learn.
If it is possible to run everything without shell scripts, then that’s all good, I’ll fork an have a play to see what I can come up with.

**Comment by SeanFarrow** [comment]
Are there binary releases for the C and C++ SDKs available? I need to use this pretty quickly and I'm having an awful time building on windows due to an issue in CMake

**Comment by MushMal** [comment]
Not currently, we are considering having a binaries for specific versions for specific OS-es with specific dependencies to be released along the side of the major version release cuts but nothing yet due to a number of issues which I am going to skip.

Meanwhile, what's the actual issue you are facing in building for windows? Are you installing the prerequisites such as pkg-config, etc.. for Windows? We have a clean Travis CI runs for Windows - some of the needed dependencies are installed as part of the travis script: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/.travis.yml#L107

**Comment by SeanFarrow** [comment]
I think I’ve got everything, PKG config is installed using strawberry perl, so I don’t think I need to do anything then but will check the script in the morning

Sent from my iPhone

On 20 Aug 2020, at 02:56, Mushegh Malkhasyan <notifications@github.com> wrote:

﻿

Not currently, we are considering having a binaries for specific versions for specific OS-es with specific dependencies to be released along the side of the major version release cuts but nothing yet due to a number of issues which I am going to skip.

Meanwhile, what's the actual issue you are facing in building for windows? Are you installing the prerequisites such as pkg-config, etc.. for Windows? We have a clean Travis CI runs for Windows - some of the needed dependencies are installed as part of the travis script: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/.travis.yml#L107

**Comment by SeanFarrow** [comment]
Just as an update, I couldn’t get this building on Windows 10 with vs2019 and Strawberry perl, as it can’t find pkg_config.
Is there any way static libs could be provided for debug/release in the near future, I’m happy to help where I can as I have a few days off.
I’ll look at the build process next weekend to see if I can’t get it building with vcpkg and I’m also going to raise an issue with the CMake folks as I’ve got something that reproduces the problem locally.

**Comment by MushMal** [comment]
We are certainly considering the binary releases but no ETA. As I mentioned it is not as straight forward with the 3rd party dependencies. Meanwhile, could you perhaps try to set your environment to mimic the same as we have in the Travis CI scripts?

**Comment by SeanFarrow** [comment]
Potentially, yes, although I am totally blind, so setting up a VM can be challenging.
Other than Strawberry perl/cmake are there any other dependencies?
Do we know what Travis installs by default?
Thanks for any help.
Sean.

**Comment by MushMal** [comment]
I am going to resolve this issue. Please consider opening a more targeted issue so we can iterate.
