### ISSUE TITLE
putMedia with result Timeout was reached: Operation too slow

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-producer-c#156]
* platform: mips

* the SDK commit version: 7f4ea67 ("Updating PIC (#145)", 2020-12-02)

* changes to the code:
  1. using createDefaultCallbacksProviderWithIotCertificate for credential provider
  2. modify put post stream files with real time frame
  3. video duration reference by real time frame's timestamp 

We have customer report issue on site: 
During put frames to KVS stream, when something going on with network. The connection may slow or even break. But the network quickly recovers. The cameras should also recover on their own when the network recovers. But they are not recovering. It's require to restart program.

Here are uart logs showing the problem:
2020-12-22 00:40:22 there is a network failure. The network came back shortly after this, but video fails to upload indefinitely. We able to stream over webrtc for live video. But proc not put frames to KVS stream any more.

For this issue I'm not reproduce in my side, and need to help for this. 
[Not_put_frames.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/5734478/Not_put_frames.txt)

**Comment by disa6302** [comment]
@henryChmn , 

I do see "getStreamData(): Indicating an EOS after last persisted ACK" message in the logs but I am unsure of the source. Can we get some VERBOSE logs to understand what the issue could be?

**Comment by henryChmn** [comment]
Update log with  VERBOSE logs
[2020-12-23 21-08-43 FT230X Basic UART.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/5738228/2020-12-23.21-08-43.FT230X.Basic.UART.log)

**Comment by MushMal** [comment]
@henryChmn have you looked at your logs? Do you have any questions in particular? You have not included any information about the asset you are using, the commit version, whether you have made any changes to the code or not. No information about your platform or the software. What is the expectation? If you have any question in particular then please ask.

the sdk default behavior is to reset the connection on the latency pressure and staleness. Do you see it doing it from the logs?

**Comment by henryChmn** [comment]
I had update request information above.

![image](https://user-images.githubusercontent.com/58592084/103065360-62aef480-45f1-11eb-8d1a-b7dbee779ac1.png)

For kinesisVideoStreamTerminated() notify, how can sample code receive it and skip the put frame loop?

**Comment by MushMal** [comment]
@henryChmn The PIC is fairly recent so should have all the latest in recovery. 

It seems you have a custom application entirely so here are some general thoughts you might find useful when debugging your application:


1) PIC/KVS streams does not expose an API that allows to get the current state. Nor, it has a callback that notifies of the state transitions. The signaling client in WebRTC has those but not the streams.
2) Looking at the log and your configuration I have some comments about the absolute frame timecode that is set to relative timecodes. Relative timecode mode is reserved for a VERY SPECIAL applications that know what they are doing
3) You are timing out not because of the network but because you are not producing frames.

Your last putKinesisVideoFrame call is made here

`12-23 21:17:08.471: 2020-12-24 02:17:07 VERBOSE putKinesisVideoFrame(): debug frame info pts: 424960000, dts: 424960000, duration: 0, size: 212, trackId: 2, isKey 0
`

Whereas you are timing out in 

`12-23 21:17:44.237: 2020-12-24 02:17:43 WARN    curlCompleteSync(): curl perform failed for url https://s-4010bf70.kinesisvideo.us-west-2.amazonaws.com/putMedia with result Timeout was reached: Operation too slow. Less than 30 bytes/sec transferred the last 30 seconds
`

The default is configured to be 30 seconds which is also happen to be the backend timeout value. 

The state machine after the timeout will move to a Ready state and will await for the next putframe call to continue to create a new session. There is no reason to call a PutMedia if there are no frames to be transmitted.

Hope this makes it clear.

**Comment by henryChmn** [comment]
In our application timecode  are reference sample code:
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/ee4eb03429f03737d9245e54f4d2fb13b08eaf80/samples/KvsAacAudioVideoStreamingSample.c#L75

Will focus in putKinesisVideoFrame relative function and  trace our producing frames routine, hope find out what happen.

Thanks for your help and happy Merry Christmas.

**Comment by henryChmn** [comment]
I found a timecode problem and will close this issue.
