### ISSUE TITLE
Frame drops while uploading FHD Video

### ISSUE THREAD

**Issue by surya-teja-p** [awslabs/amazon-kinesis-video-streams-producer-c#201]
Hi,

I'm uploading FHD video using KvsAacAudioVideoStreamingSample application, but frames are getting dropped. As suggested in closed issues, I have increased `DEFAULT_DEVICE_STORAGE_SIZE` to 256 in `DeviceInfoProvider.h`, but still I get same errors.  Please find attached [log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/6090389/log.txt)

**Comment by surya-teja-p** [comment]
Any suggestions?

**Comment by hassanctech** [comment]
2021-03-05 11:57:41 INFO    stopKinesisVideoStreamSync(): Synchronously stopping Kinesis Video Stream 000000000142a678.
.... 
2021-03-05 11:59:41 ERROR   stopStreamSync(): Failed to stop Kinesis Video Stream - timed out.
2021-03-05 11:59:41 ERROR   stopKinesisVideoStreamSync(): operation returned status code: 0x0000000f
Failed with status 0x0000000f
2021-03-05 11:59:41 INFO    freeKinesisVideoStream(): Freeing Kinesis Video stream.


It looks like you call `stopStreamSync` but it times out, at which point everything is dropped.  This is expected behavior.  Have you modified the sample to call `stopKinesisVideoStreamSync` as indicated in the logging?

**Comment by surya-teja-p** [comment]
@hassanctech No, I'm not calling `stopKinesisVideoStreamSync`. After joining threads `stopKinesisVideoStreamSync` is called as in example application.

Yes, I had modified only to load video and audio frames in thread instead of before calling the thread.

I observed it is working for high bandwidth, but failing in low bandwidth. May be `streamStopTime` is causing this issue.

**Comment by surya-teja-p** [comment]
Hi @hassanctech 

Yes, it is 20s duration and earlier logs which I had shared are on low bandwidth. I think this issue I'm facing with specific network, when I switch network there no frame drops, but I'm loosing last fragment though. I checked on sample application without any modifications, but still lost the last fragment. What ever duration I choose I’m loosing the last fragment.

**Comment by MushMal** [comment]
StopSync should return ok in order to receive the ack for the last fragment. Debug your solution first. I am guessing that your dropped frames are due to low bandwidth. Try the sample video only stream that uploads frames - those have low density and should work ok. Run the sample on high bandwidth network to eliminate the network pressures

**Comment by surya-teja-p** [comment]
Hi, 

I debugged and found that producer is generating video without last fragment in local dumped video file. I ran logs in the verbose level, which showed putKinesisVideoFrame uploaded upto 18.12s and stopped the stream. 

`VERBOSE putKinesisVideoFrame(): debug frame info pts: 181200000, dts: 181200000, duration: 0, size: 66407, trackId: 1, isKey 0`

`INFO    stopKinesisVideoStreamSync(): Synchronously stopping Kinesis Video Stream 0000000001acf0d8.`

**Comment by MushMal** [comment]
Local file is generated when the networking is loading data to send over the wire. This could mean that either your media source is not producing the frames or the networking can’t stream out the last fragments. Recommend debugging your network stack. As mentioned numerous times, try to run a low density stream first to ensure the correctness of your application without network pressures

**Comment by surya-teja-p** [comment]
I couldn't find any network pressure callback in logs, and I'm streaming on good bandwidth of 40Mbps upload. I'm using KinesisAudioVideoSample application to stream for FHD and SD resolution, but even I'm loosing last fragment at SD resolution.

**Comment by jdelapla** [comment]
Hello @surya-teja-p , are you still experiencing this issue or have you found a resolution?

**Comment by disa6302** [comment]
Closing since it has gone stale.
