### ISSUE TITLE
kinesisVideoStreamParseFragmentAck(): operation returned status code: 0x52000047

### ISSUE THREAD

**Issue by rdkcteam** [awslabs/amazon-kinesis-video-streams-producer-c#205]
Question - 
Under some slow network scenarios we are seeing this error code 0x52000047 frequently along with buffer overflow and frame drop callbacks.  Does this impact player playback experience since frames are being dropped in producer side ?
How can this be mitigated ?

[ERROR][2021-03-21 21:37:31] kinesisVideoStreamParseFragmentAck(): operation returned status code: 0x52000047
[ERROR][2021-03-21 21:37:31] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 510700000
[ERROR][2021-03-21 21:37:31] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 476330000
[ERROR][2021-03-21 21:37:32] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 442640000
[ERROR][2021-03-21 21:37:33] SampleStreamCallbackProvider::bufferDurationOverflowPressureHandler invoked : remaining_duration : 32000000
[ERROR][2021-03-21 21:37:33] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 448000000
[ERROR][2021-03-21 21:37:33] SampleStreamCallbackProvider::bufferDurationOverflowPressureHandler invoked : remaining_duration : 26580000
[ERROR][2021-03-21 21:37:33] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 453700000
[ERROR][2021-03-21 21:37:34] SampleStreamCallbackProvider::bufferDurationOverflowPressureHandler invoked : remaining_duration : 21040000
[ERROR][2021-03-21 21:37:34] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 459530000
[ERROR][2021-03-21 21:37:34] SampleStreamCallbackProvider::bufferDurationOverflowPressureHandler invoked : remaining_duration : 15060000
[ERROR][2021-03-21 21:37:34] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 464660000
[ERROR][2021-03-21 21:37:35] SampleStreamCallbackProvider::bufferDurationOverflowPressureHandler invoked : remaining_duration : 9940000
[ERROR][2021-03-21 21:37:35] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 470660000
[ERROR][2021-03-21 21:37:35] SampleStreamCallbackProvider::bufferDurationOverflowPressureHandler invoked : remaining_duration : 4000000
[ERROR][2021-03-21 21:37:35] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 476180000
[ERROR][2021-03-21 21:37:36] SampleStreamCallbackProvider::droppedFrameReportHandler : dropped_frame_timecode : 10865977550000
[ERROR][2021-03-21 21:37:36] SampleStreamCallbackProvider::droppedFrameReportHandler : dropped_frame_timecode : 10865982910000
[ERROR][2021-03-21 21:37:36] SampleStreamCallbackProvider::droppedFrameReportHandler : dropped_frame_timecode : 10865988910000
[ERROR][2021-03-21 21:37:36] SampleStreamCallbackProvider::droppedFrameReportHandler : dropped_frame_timecode : 10865994200000
[ERROR][2021-03-21 21:37:36] SampleStreamCallbackProvider::droppedFrameReportHandler : dropped_frame_timecode : 10865999960000
[ERROR][2021-03-21 21:37:36] SampleStreamCallbackProvider::droppedFrameReportHandler : dropped_frame_timecode : 10866005710000
[ERROR][2021-03-21 21:37:36] SampleStreamCallbackProvider::droppedFrameReportHandler : dropped_frame_timecode : 10866010930000
[ERROR][2021-03-21 21:37:36] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 441990000
[ERROR][2021-03-21 21:37:36] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 447970000
[ERROR][2021-03-21 21:37:37] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 453080000
[ERROR][2021-03-21 21:37:38] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 458930000
[ERROR][2021-03-21 21:37:38] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 464600000
[ERROR][2021-03-21 21:37:39] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 469980000
[ERROR][2021-03-21 21:37:39] SampleStreamCallbackProvider::streamLatencyPressureHandler : buffer_duration - 475970000

**Comment by hassanctech** [comment]
This error code 0x52000047 is returned when by the time a fragment ACK is received the fragment has been removed from the local store.  This in it of itself is not an issue, the issue will arise in the case the ACK was an error ACK in which case we might have tried to retry but now it's been dropped from the memory view (due to the buffer being filled).

You should log the type of ACK you're getting, only in the case of ERROR ack is it actually an issue and of course in that case it would impact playback.  But if the ACK you get back is a persisted ACK then you can safely ignore the frame dropped messages because they would have been successfully ingested by the backend.

If you're running into a case where network is so bad that you're dropping messages before you can get the ACK back then possibly you may need to increase your buffer size to avoid this in the case of ERROR ack so the fragment is still available to retry so you don't lose the data.

**Comment by rdkcteam** [comment]
With above explanation we assume that error 0x52000047 is harmless since we are not receiving fragment error callback but persisted callbacks and it won't cause any issue in playback side.

Do you mean that even though frame drop callbacks are being invoked, frames have already been ingested to backend ?

**Comment by hassanctech** [comment]
I did some more digging I was wrong so if the frame drop callback is being invoked the frame is actually being dropped.   There is an edge case where since the ACKs are at a fragment level and the dropFrame is at a frame level, we could be mid fragment streaming when the frames start to get dropped, but definitely some frames will be missing which means playback will be impacted depending on how your player deals with missing frames.

If you do not see the drop frame callback though then you should not be missing frames and of course the playback should be fine.

**Comment by rdkcteam** [comment]
@hassanctech  Thanks for your explanation.

**Comment by rdkcteam** [comment]
Closing this issue due to provided explanation.
