### ISSUE TITLE
[QUESTION] What is meant with the "buffer duration" parameter with `createRealtimeAudioVideoStreamInfoProvider()`

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-producer-c#278]
The `create*InfoProvider()` expects a _buffer duration_ but I'm wondering what the meaning of this is? 

What would be a correct value be for a real time 30fps audio/video stream?

```C
/**
 * Creates Stream Info for RealTime Streaming Scenario using default values.
 *
 * NOTE: The caller is responsible for releasing the structure by calling
 * the corresponding free API.
 *
 * @param[in,opt] PCHAR stream name
 * @param[in] UINT64 retention in 100ns time unit
 * @param[in] UINT64 buffer duration in 100ns time unit
 * @param[out] PStreamInfo* Constructed object
 *
 * @return STATUS code of the execution
 */
PUBLIC_API STATUS createRealtimeVideoStreamInfoProvider(PCHAR, UINT64, UINT64, PStreamInfo*);
```

**Comment by MushMal** [comment]
This is the buffer duration in default time units (100ns) on how long to buffer the data in the client. This value should be used in conjunction with the physical buffer size for the content store. Note, the content store is shared among all of the streams in the client. There are some helper APIs that allow determining how much storage (approximately) a certain stream configuration would require for a given buffer and vice versa. 

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L586

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L638

**Comment by roxlu** [comment]
Thanks @MushMal.

1.  When you say "how long to buffer the data in the client", does that mean that when I set a buffer duration of something like 10 seconds, that there will be 10 seconds of media data kept in memory before it's sent to KVS?

2. If that's the case what's the purpose of this? 

3. Why doesn't the library directly send data to KVS? Is this because of frame ordering / fragmenting?

**Comment by MushMal** [comment]
The buffer is needed on the client to "weather" the poor network conditions. If the network speed and the latency allows, the client will stream bits as fast as they are produced by the media pipeline. The recommendation is to select something larger than 10 seconds to accommodate for a few GoP worth of data in order to allow re-streaming in case of network interruptions. There is a documentation describing the buffering (https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/buffering.md) and how to calculate what you need for your scenario (https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-reference-structures-producer.html)

**Comment by roxlu** [comment]
Thanks @MushMal
