### ISSUE TITLE
How to get URL from kinesis video streams with GetHLSStreamingSessionURL

### ISSUE THREAD

**Issue by Paddyd101** [awslabs/amazon-kinesis-video-streams-producer-c#289]
HI, I am trying to get a URL to view my video on kinesis video streams with getHLSStreamingSessionURL.

On postman I have created a POST call to 'https://endpoint/getHLSStreamingSessionURL

On postman I get a 200 response but the response body is :

```
{
    "Output": {
        "__type": "com.amazon.coral.service#UnknownOperationException"
    },
    "Version": "1.0"
}
```
And here is my request body:

```
{
   "ContainerFormat": "FRAGMENTED_MP4",
   "DiscontinuityMode": "ON_DISCONTINUITY",
   "DisplayFragmentTimestamp": "ALWAYS",
   "Expires": 300,
   "HLSFragmentSelector": { 
      "FragmentSelectorType": "PRODUCER_TIMESTAMP",
       "TimestampRange": { 
        "EndTimestamp": 1646055362163,
        "StartTimestamp": 1646055362143
      }
   },
   "PlaybackMode": "ON-DEMAND",
   "StreamName": "DEV_videoStreamTest"
}
```
Can anyone suggest what is wrong with my http request?

**Comment by niyatim23** [comment]
Hi @Paddyd101, `"PlaybackMode": "ON_DEMAND"`, you've used `-` instead of an `_` here, can you please check if updating that fixes the issue for you? Other than that your request seems correct and this does not look like a KVS SDK issue.
I also suggest you to check your Postman configuration under "Authorization" to work with AWS Signatures.

Closing assuming answered, feel free to reopen it in case of further questions
