### ISSUE TITLE
[QUESTION] Is it possible to create mutliple simultaneous streams using this SDK? 

### ISSUE THREAD

**Issue by karankishore** [awslabs/amazon-kinesis-video-streams-producer-c#377]
Is it possible to create mutliple simultaneous streams using this SDK? If yes, is there a sample for the same?

**Comment by disa6302** [comment]
Yes. You can create multiple streams using the producer SDK. We do not have a sample in this repo, but we do have a sample in the CPP repo which might be helpful: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/v3.3.1/samples/kvs_gstreamer_multistream_sample.cpp

Essentially, you would invoke any stream specific functions in a loop like here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/v3.3.1/samples/kvs_gstreamer_multistream_sample.cpp#L436

**Comment by hassanctech** [comment]
There is a dedicated API to create a stream which takes in a client handle (to associate it with a client) and a StreamInfo which contains information about the Stream and then returns the streamHandle:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/samples/KvsVideoOnlyStreamingSample.c#L126

You just need to create a new StreamInfo for each stream you want to create and then you need to store the returned streamHandle because when you start sending video data via the `putKinesisVideoFrame` API you provide it the stream handle for the stream you want to send data for.
